baseURL = 'https://1980204066.github.io.git'
languageCode = 'en-us'
title = '不动闲心 の blog'
theme = "m10c"
[[params]]
author = 'leisuremood'
description = '劝僧一杯酒，共看青青山。酣然万象灭，不动心印闲。'
avatar = '/avatar.jpeg'
[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"
[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/vaga"
# [[menu]]
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"

